version: "3.9"

services:
   project:
      build:
         context: .
         dockerfile: Dockerfile_web.dev
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - 8005:8000
      env_file:
        - .env
      restart: "on-failure"
      # depends_on:
      #   - postgres-db
      networks:
        - project-network
   
networks:
   project-network:
      driver: bridge
      